=== hmhicham/xml-project/tp-daxml-main/xml/Config.dtd
<!ELEMENT config (header, nav)>
<!ELEMENT header (img, h1)>
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #REQUIRED>
<!ATTLIST img alt CDATA #IMPLIED>
<!ELEMENT h1 (#PCDATA)>
<!ELEMENT nav (student+)>
<!ELEMENT student (nom, prenom, specialite, section, groupe, email)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT specialite (#PCDATA)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT groupe (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== hmhicham/xml-project/tp-daxml-main/xml/Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "Config.dtd">

<config>
    <header>
        <img src="images/banner.jeg" alt="Travel Site Banner"/>
        <h1>Growth Agence</h1>
    </header>
    <nav>
        <student>
            <nom>Tayem</nom>
            <prenom>Mohammad Ghaith</prenom>
            <specialite>TI</specialite>
            <section>1</section>
            <groupe>2</groupe>
            <email>gayethtayem@gmail.com</email>
        </student>
        <student>
            <nom>Hamoul</nom>
            <prenom>Hichem</prenom>
            <specialite>TI</specialite>
            <section>1</section>
            <groupe>2</groupe>
            <email>h.hamoul@mail.dz</email>
        </student>
    </nav>
</config>
